version: '3.8'

services:
  web:
    build: .
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - static_volume:/app/static
    expose:
      - 8000
    environment:
      - DEBUG=0
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: 